# https://docs.travis-ci.com/user/customizing-the-build/
language: cpp

sudo: required

matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      env: Tr_Xcode_Version="9.2"
    - os: osx
      osx_image: xcode9.3beta
      env: Tr_Xcode_Version="9.3beta"

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install boost curl enet libogg glew gloox icu4c libogg libpng libsodium libvorbis libiconv libxml2 miniupnpc sdl2 wxWidgets zlib; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew outdated cmake || brew upgrade cmake; brew outdated pkgconfig || brew upgrade pkgconfig; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew link --force gettext; fi

script:
  - cd build/workspaces
  - ./update-workspaces.sh --disable-atlas
  - cd gcc
  - make
