# https://docs.travis-ci.com/user/customizing-the-build/
language: cpp

sudo: required

matrix:
  include:
    - os: osx
      osx_image: xcode9.3beta
      env: Tr_Xcode_Version="9.3beta"

script:
  - cd libraries/osx
  - ./build-osx-libs.sh
  - cd ../../build/workspaces
  - ./update-workspaces.sh --disable-atlas
  - cd gcc
  - make
