# https://docs.travis-ci.com/user/customizing-the-build/
language: cpp

sudo: required

matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      env: Tr_Xcode_Version="9.2"
    - os: osx
      osx_image: xcode9.3beta
      env: Tr_Xcode_Version="9.3beta"

script:
  - cd build/workspaces
  - ./build-osx-bundle.sh
  - ./update-workspaces.sh --disable-atlas
  - cd gcc
  - make
