# https://docs.travis-ci.com/user/customizing-the-build/
language: cpp

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      env: Tr_Compiler_Version="7"
      dist: trusty
#    - os: osx
#      osx_image: xcode9.2
#      env: Tr_Xcode_Version="9.2"
#    - os: osx
#      osx_image: xcode9.3beta
#      env: Tr_Xcode_Version="9.3beta"

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install enet libogg glew gloox libogg libsodium libvorbis libxml2 miniupnpc sdl2; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew outdated cmake || brew upgrade cmake; brew outdated pkgconfig || brew upgrade pkgconfig; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./.travis_before_install.sh; fi
script:
  - build/workspaces/update-workspaces.sh
  - make -C gcc
